<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class StkItem extends Model
{
    use HasFactory;

    protected $connection = 'sqlsrv';

    protected $table = 'StkItem';

    protected $primaryKey = 'StockLink';

    protected $fillable = [
        'StockLink',
        'Code',
        'Description_1',
        'Description_2',
        'Description_3',
        'ServiceItem',
        'ItemActive',
        'WhseItem',
        'erialItem',
        'DuplicateSN',
        'StrictSN',
        'BomCode',
        'SMtrxCol',
        'PMtrxCol',
        'cModel',
        'cRevision',
        'cComponent',
        'dDateReleased',
        'dStkitemTimeStamp',
        'iInvSegValue1ID',
        'iInvSegValue2ID',
        'iInvSegValue3ID',
        'iInvSegValue4ID',
        'iInvSegValue5ID',
        'iInvSegValue6ID',
        'iInvSegValue7ID',
        'cExtDescription',
        'cSimpleCode',
        'bCommissionItem',
        'bLotItem',
        'iLotStatus',
        'bLotMustExpire',
        'iItemCostingMethod',
        'iEUCommodityID',
        'iEUSupplementaryUnitID',
        'fNetMass',
        'iUOMStockingUnitID',
        'iUOMDefPurchaseUnitID',
        'iUOMDefSellUnitID',
        'fStockGPPercent',
        'cEachDescription',
        'cMeasurement',
        'fBuyLength',
        'fBuyWidth',
        'fBuyHeight',
        'fBuyArea',
        'fBuyVolume',
        'cBuyWeight',
        'cBuyUnit',
        'fSellLength',
        'fSellWidth',
        'fSellHeight',
        'fSellArea',
        'fSellVolume',
        'cSellWeight',
        'cSellUnit',
        'bOverrideSell',
        'bUOMItem',
        'bDimensionItem',
        'bVASItem',
        'bAirtimeItem',
        'StkItem_iBranchID',
        'StkItem_dCreatedDate',
        'StkItem_dModifiedDate',
        'StkItem_iCreatedBranchID',
        'StkItem_iModifiedBranchID',
        'StkItem_iCreatedAgentID',
        'StkItem_iModifiedAgentID',
        'StkItem_iChangeSetID',
        'StkItem_Checksum',
        'ulIISupplierCategory',
        'ufIIm3',
        'ufIIlength',
        'ufIIwidth',
        'ufIIheight',
        'ulIIFactorType',
        'ulIIFactorCategory',
        'ufIIImportFactor',
        'ufIIFactorMargin',
        'ufIIFactorVAT',
        'ulIISalesCategory',
        'ulIISalesSubCategory',
        'bSyncToSOT',
        'uiIIModelLifeCol',
        'uiIIModelLifeMon',
        'uiIIStYield',
        'ulIITonType',
        'ulIICoo',
        'bImportedServices',
        'ufIISalesMargin',
        'ufIIweight',
        'ucIITaxHSCode',
        'ucIIScheme',
        'ufIIVolume',
        'iAttributeGroupID',
        'xAttribute',
        'iMajorIndustryCodeID',
    ];

    public $timestamps = false;
}